SciML/ModelingToolkitStandardLibrary.jl

src/Blocks/Blocks.jl
src/Blocks/nonlinear.jl
test/runtests.jl
test/test_nonlinear.jl

This PR adds two common nonlinear input-output blocks

Add Saturation and DeadZone blocks

---

docs/src/API/magnetic.md
docs/src/API/mechanical.md
docs/src/index.md
src/Mechanical/Mechanical.jl
src/Mechanical/Rotational/Rotational.jl
src/Mechanical/Rotational/components.jl
src/Mechanical/Rotational/sources.jl
src/Mechanical/Rotational/utils.jl
src/ModelingToolkitStandardLibrary.jl
test/Mechanical/rotational.jl
test/runtests.jl

Adds rotational components

---

test/Thermal/demo.jl
test/Thermal/thermal.jl

DAE observed solution indexing is broken right now. https://github.com/SciML/ModelingToolkit.jl/pull/1575

Upgrade to new MTK

---

docs/make.jl
docs/src/API/electrical.md

Sry, missed that in the previous PR.

Adds missing link in doc

---

src/Electrical/Analog/ideal_components.jl
src/Electrical/utils.jl
test/Electrical/analog.jl

And, use `TwoPort` in `IdealOpAmp`

Add `Short` in Analog and `TwoPort` in Electrical

---

docs/src/API/blocks.md
docs/src/API/electrical.md
docs/src/API/magnetic.md
docs/src/API/mechanical.md
docs/src/API/thermal.md

To make navigating the API docs quicker

Add contents and index to API pages

---

Project.toml
docs/src/API/linear_analysis.md
src/Blocks/Blocks.jl
src/Blocks/analysis_points.jl
test/Blocks/test_analysis_points.jl
test/runtests.jl

Supersedes #112 
Waiting for 
- https://github.com/SciML/ModelingToolkit.jl/pull/1839

Update analysis points to use find/replace in MTK

---

docs/src/tutorials/dc_motor_pi.md

Should not look so silly anymore. ;)

Reduces disturbance step

---

src/Blocks/analysis_points.jl

For MORE PERFORMANCE when linearizing repeatedly :)

implement `linearize` using `linearization_function`

---

src/Blocks/Blocks.jl
src/Blocks/sources.jl
test/Blocks/math.jl
test/Blocks/sources.jl

This is useful to input data from, e.g., an interpolator

add `TimeVaryingFunction` source block

---

src/Blocks/continuous.jl
test/Blocks/continuous.jl

somewhere the original implementation got inverted

fix `Td` definition in LimPID

---

.github/workflows/Downstream.yml

Some MTK tests rely on MTKStdlib as well.

Add MTK to downstream tests

---

docs/make.jl
docs/src/API/linear_analysis.md

To have it accessible locally and to avoid 404 `@ref` links

add linearize docstring

---

src/Blocks/sources.jl
src/Hydraulic/IsothermalCompressible/components.jl
src/Hydraulic/IsothermalCompressible/utils.jl
test/Hydraulic/isothermal_compressible.jl

DynamicVolume now capable of minimum volume flow shut off with damping region and the inclusion of flow resistance and inertia thru the volume with discretization.

Improvements to DynamicVolume component

---

docs/src/API/electrical.md

Fixes https://github.com/SciML/ModelingToolkitStandardLibrary.jl/issues/177

Update docs: electrical analog sources

---

Project.toml

chore: bump version to v2.3.0

---

test/Mechanical/translational.jl

Fix test for `Mechanical.Translational.Free` component

---

test/runtests.jl

It's already there a few lines below

Don't include the chua circuit demo twice in tests

---

test/multi_domain.jl

Remove duplicate import line

---

src/Blocks/math.jl
src/Blocks/sources.jl
src/Blocks/utils.jl
test/Blocks/utils.jl
test/runtests.jl

fix: fix guesses for `Real*Input` and `Real*Output`

---

src/Electrical/utils.jl

Remove unnecessary defaults

---

.github/workflows/Tests.yml

We should run tests for PRs opened to non-main and non-release-* branches too
~- [ ] Appropriate tests were added~
~- [ ] Any code changes were done in a way that does not break public API~
~- [ ] All documentation related to code changes were updated~
~- [ ] The new code follows the
[COLPRAC](https://github.com/SciML/COLPRAC).~
~- [ ] Any new documentation only uses public API~

ci: run tests for PRs targeted to any branch

---

docs/src/API/blocks.md
docs/src/tutorials/custom_component.md
docs/src/tutorials/dc_motor_pi.md
docs/src/tutorials/rc_circuit.md
docs/src/tutorials/thermal_model.md

1. Remove hard coded images
2. Small cleanups
3. Fix custom component tutorial - It is failing on master https://github.com/SciML/ModelingToolkitStandardLibrary.jl/actions/runs/10060925603/job/27809687823

docs: clean up docs and fix custom component tutorial

---

docs/src/tutorials/custom_component.md

docs: update custom component tutorial with `@mtkmodel`

---

docs/src/tutorials/custom_component.md
docs/src/tutorials/dc_motor_pi.md
docs/src/tutorials/rc_circuit.md
docs/src/tutorials/thermal_model.md

Refactors DCMotor, RC Circuit, Heat conduction model

Refactor all tutorials with `@mtkmodel` and `@mtkbuild`

---

docs/src/API/mechanical.md
src/Mechanical/Rotational/Rotational.jl
src/Mechanical/Rotational/sources.jl
test/Mechanical/rotational.jl

add Rotational.Position source

---

docs/src/API/hydraulic.md

Added missed lines in hydraulic.md for new components - Open, FlowDivider, Valve, SpoolValve, SpoolValve2Ways, Actuator
@bradcarman @ChrisRackauckas

added missing doc links in hydraulic.md

---

docs/src/tutorials/dc_motor_pi.md

Fixes https://github.com/SciML/ModelingToolkitStandardLibrary.jl/issues/328

Fix DC Motor tutorial

---

test/Thermal/piston.jl

test: fix thermal piston test

---

test/Mechanical/rotational.jl
test/Thermal/thermal.jl

test: fix tests of analytically solved systems
