- .github/workflows/CI.yml
The CI workflow runs only when pushes are made/PRs are opened to `master`. Since MTKStdLib has a `main` branch and not a `master` branch, this would mean that the CI never runs. Fix the CI script accordingly to have it run as expected.
> fix CI workflow

- src/Blocks/continuous.jl
The nl solver errored if the terms were included with coefficient 0
This PR also introduces a safeguard for the default value of the anti-windup tracking coefficient.
> remove D equations from PID if D term turned off

- Project.toml
Reverts SciML/ModelingToolkitStandardLibrary.jl#23
> Revert "CompatHelper: bump compat for ModelingToolkit to 8, (keep existing compat)"

- src/Blocks/continuous.jl
to enable MTKstdlib as drop-in replacement for other ss modeling tools.
> Provide classical constructor for `StateSpace`

- src/Blocks/math.jl
- src/Electrical/Analog/ideal_components.jl
- src/Electrical/Analog/sources.jl
- src/Mechanical/Rotational/components.jl
- src/Thermal/HeatTransfer/ideal_components.jl
- src/Thermal/HeatTransfer/sources.jl
This PR removes the most arbitrary defaults I could find. The rational being that defaults are only useful if they apply to a vast majority of people. Values that are highly likely to be changed should not be associated with defaults since this can hide logical bugs in the model.
Some details
1. Remove defaults that lead to a component being a noop, e.g., gain=1
2. Component values arbitrarily set to 1, e.g., the capacitance of a capacitor.
3. I have *not* removed default amplitude 1 of periodic signals since it's common to change this with a subsequent gain block etc. 
4. Some defaults that are somewhat arbitrary are left, like `T_start=293.15 + 20` being *close* to a common room temperature.
> Remove some arbitrary defaults

- src/Thermal/HeatTransfer/ideal_components.jl
To go from Kelvin scale to Celsius scale, add `273.15`, not `293.15`.
> Correct room temperature value

- src/Blocks/Blocks.jl
- src/Blocks/sources.jl
- test/Blocks/sources.jl
- test/Thermal/thermal.jl
- Adds `smooth` option for sources in Blocks. For `Sine`, `Cosine`, `ExpSine`, `Step`, `Ramp`
- Adds Square and Triangular sources
> Add `smooth` sources in `Blocks` + Add `Square` and `Triangular` sources

- src/Blocks/math.jl
- src/Blocks/utils.jl
- src/Thermal/HeatTransfer/ideal_components.jl
- test/Blocks/math.jl
Removes pesky warnings that the connector contains (non-flow, non-stream, non-input, non-output) variables but no flow variable.
> Adds input/output meta data

- docs/pages.jl
- docs/src/API/thermal.md
- docs/src/index.md
- docs/src/tutorials/thermal_model.md
- src/Mechanical/Rotational/Rotational.jl
- src/Thermal/HeatTransfer/ideal_components.jl
- src/Thermal/HeatTransfer/sensors.jl
- src/Thermal/HeatTransfer/sources.jl
- src/Thermal/Thermal.jl
- src/Thermal/utils.jl
- test/Thermal/demo.jl
- test/Thermal/thermal.jl
- Renames ports of `ConvectiveResistor` (`solidport` to `solid` and `fluidport` to `fluid`) to be the same as `ConvectiveConductor`.
- `PrescribedHeatFlow`
- `PrescribedTemperature`
> Make thermal models ODEs again

- src/Blocks/continuous.jl
- test/Blocks/continuous.jl
This PR adds an option to the `FirstOrder` filter such that it can operate as a highpass filter instead of a lowpass filter. The simple relation
```julia
highpass(u) = u - lowpass(u)
```
is used
> allow `FirstOrder` to operate as highpass instead of lowpass

- Project.toml
- docs/Project.toml
- docs/pages.jl
- docs/src/API/linear_analysis.md
- src/Blocks/Blocks.jl
- src/Blocks/analysis_points.jl
- test/Blocks/test_analysis_points.jl
- test/Mechanical/rotational.jl
This PR adds something called an `AnalysisPoint`. These are used for linear analyses, such as 
- Computing sensitivity functions.
- Computing complementary sensitivity functions.
- Computing loop-transfer functions.
- Linearizing systems between predefined analysis points.
- Open loops
An `AnalysisPoint` can be created explicitly, but also automatically when `connect`ing an output to an input. Analysis points are causal, and are thus defined in the `Blocks` submodule. They thus expect connections of type `Blocks.RealInput` and `Blocks.ReaOutput`. 
- ~The current state of the PR does not handle namespaces and subsystems properly. In particular, I'm unsure about the proper way of modifying equations and namespaces when changing the equations in a system with subsystems.~ Namespaces are now …
> Add analysis points

- src/Blocks/continuous.jl
* backtick fix
* spelling of overdamping and underdamping without hyphen, following https://en.wikipedia.org/wiki/Damping
> docstring backtick fix

- src/Blocks/analysis_points.jl
- test/Blocks/test_analysis_points.jl
This PR adds the possibility to open loops in analysis points before computing a sensitivity function. It also solves a number of namespacing bugs, exposed by the added tests
> Allow loop openings in all sensitivity functions

- src/Blocks/continuous.jl
- src/Blocks/math.jl
- src/Blocks/nonlinear.jl
- src/Blocks/sources.jl
- src/Blocks/utils.jl
- src/Mechanical/Rotational/components.jl
- src/Mechanical/Rotational/utils.jl
This PR adds `[description = "sting"]` to a number of variables and parameters in the Blocks and Rotational modules. Other modules will come in separate PRs.
This serves two purposes
1. Make models from model libraries easier to work with. Without a description, it's hard to know what a variable called `k` deep inside a model does, in particular if the model comes from a library.
2. Illustrate best practices. People are likely to look to MTKstdlib to learn how to build component libraries, and I hope to establish adding variable descriptions as a best practice people follow.
> add descriptions to variables and parameters

- src/Blocks/analysis_points.jl
Analysis points are supposed to be used with `RealInput/RealOutput`, and those both have an inner variable called `u`. This PR attempts to connect other kinds of components as well, but throws an error if there is more than one state variable, in which case which one is referred to by the AP is ambiguous.
> more robust detection of analysis-point variable

- src/Blocks/analysis_points.jl
- test/Blocks/test_analysis_points.jl
This PR does two similar things
- Handle analysis points that appear in array-valued `connect` statements
- Support getting multivariate sensitivity functions by providing an array of analysis-point names
This together makes it much easier to analyze multiple-input, multiple output (MIMO) closed-loop systems.
This PR handles the sensitivity functions, a follow-up PR will address also the linearization functions
Depends on
- #134
> make sensitivity functions work for multivariate signals

- Project.toml
- src/Electrical/Digital/logic.jl
- src/Electrical/Digital/logic_vectors.jl
- src/Electrical/Digital/tables.jl
- src/Electrical/Electrical.jl
- test/Electrical/digital.jl
- test/runtests.jl
First in series of PRs to implement the entire IEEE.Std_logic_1164 in Julia
----- 
This PR will be followed up to add things like:
- Resolution table
- Inter-conversions from one range of logic-levels to other range
- Digital sources, clocks
- High level DiscreteSystems of gates
- And then revival of Adders, En(/De)coders, (De)Muxes
> Digital: Adds `Logic` and defines 9 logic levels, `StdULogicVector`, and `StdLogicVector`

- test/Blocks/continuous.jl
- test/Blocks/math.jl
- test/Blocks/nonlinear.jl
- test/Blocks/sources.jl
- test/Electrical/analog.jl
- test/Electrical/digital.jl
- test/Magnetic/magnetic.jl
- test/Mechanical/rotational.jl
- test/Thermal/demo.jl
- test/Thermal/thermal.jl
- test/chua_circuit.jl
- test/demo.jl
- test/multi_domain.jl
Refactor the return code from `:Success` -> `ReturnCode.Success`
Fixes: https://github.com/SciML/ModelingToolkitStandardLibrary.jl/actions/runs/4205971179/jobs/7298817614#step:6:456
> refactor: `:Success` -> `ReturnCode.Success`

- src/Mechanical/Mechanical.jl
- src/Mechanical/Rotational/Rotational.jl
- src/Mechanical/Rotational/sources.jl
- src/Mechanical/Rotational/utils.jl
- src/Mechanical/TranslationalModelica/TranslationalModelica.jl
- src/Mechanical/TranslationalModelica/components.jl
- src/Mechanical/TranslationalModelica/sources.jl
- src/Mechanical/TranslationalModelica/utils.jl
- test/Mechanical/rotational.jl
- test/Mechanical/translational_modelica.jl
This PR adds a version of the `Mechanical.Translational` that is more similar to the modelica versions than the two existing `Mechanical.Translational` and `Mechanical.TranslationalPosition`. There are several strong motivations for staying closer to the modelica equivalents: 
The multibody library uses the Translational library, and any deviation increases the multibody implementation effort many fold, as well as making it much more likely that we introduce bugs in the process. A graphical user interface becomes similarly more difficult to implement when a translation step is required between the open standard and our implementation, for us to be able to reuse existing assets. Lastly, the burden on existing modelica users who want to transition increases if we change variable names and …
> Add Translational library similar to MSL

- src/Blocks/Blocks.jl
- src/Blocks/continuous.jl
- src/Blocks/nonlinear.jl
- src/Mechanical/Rotational/Rotational.jl
- src/Mechanical/Rotational/components.jl
- src/ModelingToolkitStandardLibrary.jl
and apply it to several argument checks. This macro skips the check in case the input argument is a symbolic variable, in which case a non-boolean would have been used in a boolean context.
> add symcheck macro

- src/Mechanical/Rotational/components.jl
Gear ratios are frequently negative
> Do not require positive gear ratio

- src/Blocks/analysis_points.jl
- test/Blocks/test_analysis_points.jl
The output signal does not have to be an analysis point like the input does. The difference lies in that to handle an input, an extra equation is added to the model, whereas to handle the output we simply create an observed function.
> allow output to be sym variable in linearize

- docs/src/API/hydraulic.md
- src/Hydraulic/Hydraulic.jl
- src/Hydraulic/IsothermalCompressible/components.jl
- src/Thermal/HeatTransfer/ideal_components.jl
- src/Thermal/utils.jl
- Closes #171 
- Adds `ConvectiveElement1D`, a partial model that defines temperature drop and heat flow rate from `solid` to `fluid`
- While here, fixes couple of typos Hydrualic -> Hydraulic
> Fix the ConvectiveConductor equation and adds `ConvectiveElement1D`

- Project.toml
- test/Blocks/test_analysis_points.jl
- test/Electrical/analog.jl
This PR contains a set of fixes to the test suite that should be always desirable.  In a separate PR, I have collected fixes that may not be desirable, but are required for running with DAECompiler.
> Fixes to test suite

- docs/src/tutorials/input_component.md
Update input_component.md: s/performative/performant/
> docs: performative -> performant

- src/Blocks/sources.jl
- src/Hydraulic/IsothermalCompressible/components.jl
- src/Mechanical/Translational/components.jl
- src/Mechanical/Translational/sources.jl
- src/Mechanical/Translational/utils.jl
- test/Blocks/sources.jl
- test/Mechanical/translational.jl
- removed extra `n::Int` parameter
- verified derivative formulation is correct
- extra code for potential AE hack implementation
> `Parameter` type optimizations

- docs/src/connectors/connections.md
- src/Hydraulic/IsothermalCompressible/components.jl
- src/Mechanical/MultiBody2D/components.jl
- src/Mechanical/Rotational/components.jl
- src/Mechanical/Rotational/sensors.jl
- src/Mechanical/Rotational/sources.jl
- src/Mechanical/Rotational/utils.jl
- src/Mechanical/Translational/Translational.jl
- src/Mechanical/Translational/components.jl
- src/Mechanical/Translational/sensors.jl
- src/Mechanical/Translational/sources.jl
- src/Mechanical/Translational/utils.jl
- src/Mechanical/TranslationalModelica/components.jl
- src/Mechanical/TranslationalModelica/sources.jl
- src/Mechanical/TranslationalModelica/utils.jl
- src/Mechanical/TranslationalPosition/components.jl
- src/Mechanical/TranslationalPosition/sources.jl
- src/Mechanical/TranslationalPosition/utils.jl
- test/Blocks/test_analysis_points.jl
- test/Hydraulic/isothermal_compressible.jl
- test/Mechanical/rotational.jl
- test/Mechanical/translational.jl
- test/Mechanical/translational_modelica.jl
- test/runtests.jl
> Refactors Mechanical module with `@mtkmodel`

- src/Blocks/math.jl
MWE:
```julia
julia> Sum(;name=:a, input.nin=2)
ERROR: syntax: invalid keyword argument name "input.nin" around REPL[8]:1
Stacktrace:
[1] top-level scope
@ REPL[8]:
julia> @macroexpand @mtkmodel Sum begin
@components begin
input = RealInput(; nin)
output = RealOutput()
end
@equations begin
output.u ~ sum(input.u)
end
end
:(Sum = (ModelingToolkit.Model)(((; name, input__nin = nothing)->begin
#= /Users/aayush/.julia/packages/ModelingToolkit/xLMQM/src/systems/model_parsing.jl:242 =#
begin
begin
input = RealInput(name = :input; nin = input__nin)
output = RealOutput(name = :output)
end
(ODESystem)((Equation)[output.u ~ sum(input.u)], t, [], []; systems = [input, output], name, gui_metadata = nothing)
end
end), Dict{Symbol, Any}(:components => [[:input, :RealInput], [:output, :RealOutput]], …
```
> docs: fix `Blocks.Sum` docstring

- src/Mechanical/TranslationalModelica/TranslationalModelica.jl
- src/Mechanical/TranslationalPosition/TranslationalPosition.jl
- It isn't implemented in those libs
I don't see any implementation of IdealGear in these libs. @baggepinnen can we just drop them or do we want to reexport Rotational.IdealGear?
> Don't export IdealGear from TranslationalPosition and TranslationalModelica

- Project.toml
- src/Blocks/sources.jl
- src/Mechanical/Translational/sources.jl
- test/Hydraulic/isothermal_compressible.jl
- test/Mechanical/translational.jl
Fixed a couple bugs/breaking changes from v2
- `Mechanical.Translational` `Position`, `Velocity`, and `Acceleration` had all changed the initial position keyword (from `s_0` to `s__u_start`).  Turns out the initial position setting is never actually needed because the `RealInput` connector should always be driven by an absolute value, therefore this keyword is removed.
- Calculating ForwardDiff derivatives with the `Blocks.SampledData` component was not working.  Included `ForwardDiff.value()` to handle `Dual` type calls
> Source bugs fixed

- docs/src/tutorials/custom_component.md
- docs/src/tutorials/rc_circuit.md
- docs/src/tutorials/thermal_model.md
This is to avoid this warning popping up in the docs:
```julia
┌ Warning: To maintain consistency with solution indexing, keyword argument vars will be removed in a future version. Please use keyword argument idxs instead.
│   caller = ip:0x0
└ @ Core :-1
```
> docs: use `idxs` instead of `vars` for plotting in tutorials

- src/Blocks/math.jl
- src/Mechanical/MultiBody2D/MultiBody2D.jl
- src/Mechanical/MultiBody2D/components.jl
- src/Mechanical/TranslationalPosition/components.jl
- src/Mechanical/TranslationalPosition/sources.jl
- test/Mechanical/multibody.jl
Note that we can infer `D(x) = D(y)` from `x = y`, but we cannot infer `x = y` from `D(x) = D(y)`, so using the lowest variable in the connector provides more information to the compiler.
> Use lowest order differentiated variables to improve state selection

- src/Blocks/math.jl
since they lead to `p::Union{Float64, Matrix{Float64}}`. Iäve tried a few different ways of `collect`ing the array variable without success, so this PR simply changes the array to a structural parameter to get something that is at least working
> avoid using array variable

- src/Blocks/continuous.jl
- test/Blocks/continuous.jl
The previous interface required the user to provide a value of `gainPI.k`, now there is an outer parameter `k` that forwards to the inner parameter. This makes `PI` consistent with the other controller definitions and avoids mentioning the internal implementation detail `gainPI`.
> improve docstring and interface to PI controller

- src/Blocks/nonlinear.jl
- src/Blocks/utils.jl
This PR makes sure to pass initial values to also connector variables (they are supposed to be equal), and by default initializes the limiter to the center of the limit band. Having the limiter in the non-saturated region by default is important for linearization, you get the zero system otherwise.
> initialize all relevant variables for SISO

- src/Blocks/continuous.jl
After playing around with the GUI a bit, I realized that some descriptions were overly verbose and at the same time not as informative as they could be.
> nicify some docstrings and descriptions

- docs/src/tutorials/custom_component.md
This corrects the misnaming of the second variable in:
https://github.com/SciML/ModelingToolkitStandardLibrary.jl/blob/a8fc0ad98c84c363e17d56d4925957c217552057/docs/src/tutorials/custom_component.md?plain=1#L134-L135
> typo: misnamed C2.v in Chua's circuit tutorial

- src/Mechanical/Translational/Translational.jl
- src/Mechanical/Translational/sensors.jl
- test/Mechanical/translational.jl
Adding AccelerationSensor which is particularly useful for measuring acceleration of masses without having to do `force/mass`.
> feat(Translational): add AccelerationSensor

- src/Blocks/continuous.jl
- src/Blocks/sources.jl
- src/Blocks/utils.jl
* Small fixes
* In https://docs.sciml.ai/ModelingToolkitStandardLibrary/dev/API/blocks/#Source-Blocks, because of an empty line between doc string and the code block, I see missing doctstring for `Cosine`
> Tiny blocks documentation updates

- .typos.toml
- docs/src/tutorials/dc_motor_pi.md
- src/Blocks/continuous.jl
- src/Blocks/math.jl
- src/Mechanical/Rotational/components.jl
- src/Mechanical/Rotational/sensors.jl
- src/Mechanical/Rotational/sources.jl
- src/Mechanical/Rotational/utils.jl
- test/Blocks/continuous.jl
- test/Blocks/nonlinear.jl
- test/Blocks/sources.jl
- test/Blocks/test_analysis_points.jl
- test/Mechanical/rotational.jl
- test/multi_domain.jl
- Defaults in rotational lib are `guess`es
- Passes du0 and u0 for tests (in Rotational, Blocks)
- Fixes the linear analysis tests and docs (related to DC Motor example)
> Rotational: default values are now guesses + fix tests

- src/Blocks/continuous.jl
* Description of parameter `x` was inserted in https://github.com/SciML/ModelingToolkitStandardLibrary.jl/pull/191 but in wrong position, move it down
* Clean up transfer function of `Derivative`.  LHS is obtained from the implementation, the added RHS is simplified and the T->0 behavior is more obvious
> docs: cleaner and more concise transfer function of Derivative()

- src/Blocks/Blocks.jl
- src/Blocks/utils.jl
- test/Blocks/test_analysis_points.jl
This adds `RealInputArray` and `RealOutputArray` components
This also changes the default values of the states in the RealInput/Output/Array components to guesses.
This is useful for using symbolic vector for input/output size to be 1. Needed for using Neural Network blocks. Ref - https://github.com/SciML/ModelingToolkitNeuralNets.jl/issues/16
> refactor(Blocks): add `RealInputArray` and `RealOutputArray`

- src/Blocks/analysis_points.jl
- test/Mechanical/multibody.jl
> Fix `states` -> `unknowns`

- src/Blocks/sources.jl
This is pretty minor, as these type instabilities in `ifelse` are taken care of by union-splitting anyway.
But I did notice them, so thought i would fix
> Improve type stability of basic sources

- src/Electrical/Analog/ideal_components.jl
With MTK@v9 the defaults act as equations duing initialization, which can lead to overconstrained systems that can't be solved in some cases.
> Switch defaults for guesses for some components

- README.md
- docs/src/connectors/connections.md
- docs/src/tutorials/custom_component.md
- docs/src/tutorials/dc_motor_pi.md
- docs/src/tutorials/rc_circuit.md
- docs/src/tutorials/thermal_model.md
Tutorials list all systems in the `ODESystem()`-function call.  This is cumbersome, and one easily forgets to append
the list after adding the actual system and its connections.
```
systems = @named begin
..
end
```
is a more user friendly pattern.
> Use `systems = @named begin .. end` idiom to define systems in tutorials

- src/Blocks/analysis_points.jl
- test/Blocks/test_analysis_points.jl
This PR fixes a few things related to analysis points
- Handle loop openings in same analysis point as input or output
- Fix for analysis points in systems with units
- utility to print all existing analysis points
cc @shobhitvoleti
> Analysis point fixes

- src/Blocks/utils.jl
- test/Blocks/test_analysis_points.jl
- test/Blocks/utils.jl
The PR
- https://github.com/SciML/ModelingToolkitStandardLibrary.jl/pull/291
was breaking, in particular, the removal of
```julia
u = collect(u)
```
from `RealInput` and `RealOutput` broke Multibody.jl
Since we have both `RealInput` and `RealInputArray`, where the latter is using symbolic arrays, I propose that we keep the old behavior of `RealInput` intact, i.e., revert the breaking change.
> Keep non-array connector variable collected

- docs/src/connectors/sign_convention.md
Otherwise, `@mtkmodel` picks the default `t` with units.
> docs: use `t_nounits` as `t`

- test/Mechanical/translational_modelica.jl
Define the models well with init pos of the mass of test components. It alleviates InitialFailure of models post removal of defaults
> Fix TranslationalModelica tests

- src/Mechanical/Translational/sensors.jl
- src/Mechanical/TranslationalPosition/TranslationalPosition.jl
- src/Mechanical/TranslationalPosition/sensors.jl
- test/Mechanical/translational.jl
- test/runtests.jl
Also fixed `ForceSensor` in Translational.
> feat: add sensors in TranslationalPosition

- src/Hydraulic/IsothermalCompressible/IsothermalCompressible.jl
Some hydraulic components developed nicely in [src/Hydraulic/IsothermalCompressible/components.jl](https://github.com/roman-timo/ModelingToolkitStandardLibrary.jl/pull/url) are not exported.
Adding default export of these components into [src/Hydraulic/IsothermalCompressible/IsothermalCompressible.jl](https://github.com/roman-timo/ModelingToolkitStandardLibrary.jl/pull/url)
Components being exported:
- Open
- Flow divider
- Valve
- Volume
- SpoolValve
- SpoolValve2Way
- Actuator
> added export of missing hydraulic components

- src/Hydraulic/IsothermalCompressible/components.jl
Added missing docstrings for hydraulic comps: Open, SpoolValve, SpoolValve2Way, Actuator
**Need to check and review by code owner!**
@ChrisRackauckas  @bradcarman
> added missing docstrings for hydraulic comps: Open, SpoolValve, SpoolValve2Way, Actuator

- src/Blocks/analysis_points.jl
add ability to modify system _after_ analysis point handling, but before linearization
This allows conversion to `JuliaSimCompiler.IRSystem` for the structural simplification
> add ability to modify system after analysis point handling

- src/Blocks/sources.jl
- src/Hydraulic/IsothermalCompressible/IsothermalCompressible.jl
- test/Blocks/sources.jl
for consistency with
- other implementations
- literature
- the other sources in the same file
> step is active at start time

- src/Mechanical/TranslationalPosition/components.jl
- src/Mechanical/TranslationalPosition/sensors.jl
- src/Thermal/HeatTransfer/ideal_components.jl
- src/Thermal/utils.jl
@avinashresearch1 Are the changes in `Thermal` appropriate?
> Fix typo in `Spring` and remove more defaults

- Project.toml
- docs/src/connectors/connections.md
- src/Blocks/nonlinear.jl
- src/Blocks/utils.jl
- src/Mechanical/Translational/components.jl
- test/Blocks/utils.jl
- test/Mechanical/translational.jl
The SISO component is an extendable component that provides `u` and `y` variables.  These should not be have defaults at the lower level, this makes building components based on them more challenging with the MTK v9 initialization system.
> Remove defaults from Blocks.SISO

- src/Blocks/continuous.jl
- src/Blocks/nonlinear.jl
- test/Blocks/continuous.jl
- test/Mechanical/translational_modelica.jl
@AayushSabharwal some tests are failing with errors like this
```julia
LimPI: Error During Test at /home/fredrikb/.julia/dev/ModelingToolkitStandardLibrary/test/Blocks/continuous.jl:232
Got exception outside of a @test
Could not evaluate value of parameter pi_controller_lim₊limiter₊u_start. Missing values for variables in expression (1//2)*(u_max + u_min).
```
There are default values for the parameters `u_max, u_min`, so it should be possible to figure out the default for `pi_controller_lim₊limiter₊u_start`
> add parameters to PID controllers

- README.md
Unless initial condition for capacitor initial voltage is given, `ODEProblem` errors
```
┌ Warning: Initialization system is underdetermined. 0 equations for 1 unknowns. Initialization will default to using least squares. To suppress this warning pass warninitializedetermined = false. To make this
│ warning into an error, pass fully_determined = true
└ @ ModelingToolkit C:\Users\jaakkor2\.julia\packages\ModelingToolkit\zfOUk\src\systems\diffeqs\abstractodesystem.jl:1294
┌ Warning: Did not converge after maxiters = 0 substitutions. Either there is a cycle in the rules or maxiters needs to be higher.
└ @ Symbolics C:\Users\jaakkor2\.julia\packages\Symbolics\8MbnV\src\variable.jl:546
ERROR: Found symbolic value -capacitor₊p₊v(t) for variable resistor₊p₊i(t). You may be missing an initial …
```
> Add capacitor initial voltage to README.md example

- docs/src/API/electrical.md
- src/Electrical/Analog/ideal_components.jl
- src/Electrical/Electrical.jl
- test/Electrical/analog.jl
- Add ideal diode component based on the Modelica implementation: [Modelica.Electrical.Analog.Semiconductors.Diode](https://reference.wolfram.com/system-modeler/libraries/Modelica/Modelica.Electrical.Analog.Semiconductors.Diode.html)
- Add diode with temperature-dependent behaviour using a `HeatPort`
> Add diode component

- src/Thermal/utils.jl
> fix: change HeatPort to allow changing the guess

- src/Blocks/Blocks.jl
This prevents conflicting exports and overwritten method definitions when using Stdlib with `AnalysisPoint` and related infrastructure defined in https://github.com/SciML/ModelingToolkit.jl/pull/3285.
> refactor: only load analysis points if not defined in ModelingToolkit

- docs/src/API/blocks.md
- src/Blocks/Blocks.jl
- src/Blocks/math.jl
- test/Blocks/math.jl
A few of the blocks developed for a parallel project being moved to the standard library
> Adding Power, Modulo, UnaryMinus, Floor and Ceil blocks 

- src/Blocks/math.jl
- test/Blocks/math.jl
> Connector name edits for Power and Modulo

- README.md
Only the Readme is updated with the newer RC circuit example using the newer syntax of @mtkbuild, @mtkmodel, etc.
> Readme updated with new RC circuit example

- Project.toml
- src/Thermal/HeatTransfer/sources.jl
- test/Thermal/thermal.jl
- Fixes issue #234
- The issue seems to be that if alpha is 0, the symbolic compiler will create an equation with 0 division
- This has been solved using an ifelse statement
- The functionality remains the same including inputs
- Not sure whether to update the docstring, so this remains as-is
- A MWE test is adapted from issue #234 as follows:
```julia 
using OrdinaryDiffEq, ModelingToolkit
using ModelingToolkitStandardLibrary.Thermal
using ModelingToolkit: t_nounits as t
@mtkmodel TestModel begin
@components begin
temp = FixedTemperature(T=300)
heatflow = …
```
> Fixes issue #234 using same inputs

- docs/src/tutorials/input_component.md
- src/Blocks/Blocks.jl
- src/Blocks/math.jl
- src/Hydraulic/IsothermalCompressible/components.jl
- src/Hydraulic/IsothermalCompressible/sources.jl
- src/Hydraulic/IsothermalCompressible/utils.jl
- src/Thermal/HeatTransfer/sources.jl
- src/Thermal/utils.jl
- test/Blocks/math.jl
- test/Blocks/test_analysis_points.jl
- test/Thermal/piston.jl
- test/Thermal/thermal.jl
> Drop ref to non-existant `p_int` and fix format

- src/Electrical/Analog/ideal_components.jl
- test/Electrical/analog.jl
Rodas4 is set as the solver.
O/p for DiodeTest:
O/p for DiodeTest in Modelica:
<image src=https://github.com/user-attachments/assets/021d16e0-9c00-4fb5-9219-4effa4070888 width=600>
O/p for Heating diode:
Automatically picked solver doesn't capture the true dynamics of the test circuits. That resulted foll. o/p:
> Fix the diode tests + Refactor with `@mtkmodel`

- src/Electrical/Analog/ideal_components.jl
- src/Electrical/Electrical.jl
- test/Electrical/analog.jl
- test/multi_domain.jl
Merge conflicts were handled for PR #349 
HeatingDiode and HeatingResistor are now removed.
> Made PR#349 mergeable

- docs/src/API/electrical.md
- src/Electrical/Analog/transistors.jl
- src/Electrical/Electrical.jl
- test/Electrical/analog.jl
[cxontributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
Adds NPN and PNP BJT transistor models based on Ebers-Moll. These models include junction capacitances for better modeling at higher frequencies, an optional substrate pin, and optionally include the Early affect. These are similar to the Modelica NPN and PNP models, but include an option for a more sophisticated linear continuation for junction capacitances. "Computer Methods for Circuit Analysis and Design" by Jiri Vlach and Kishore Singhal (https://link.springer.com/book/9780442011949) was used as a reference.
> Add NPN and PNP BJT transistor models 

- docs/src/tutorials/input_component.md
This is really a question maskerading as a PR, but given that `?connect` says:
>   PLEASE NOTE: The connection is assumed to be causal, meaning that
> 
>   `connect(C.output, :plant_input, P.input)`
> 
>   is correct, whereas
> 
>   `connect(P.input, :plant_input, C.output)`
> 
>   typically is not (unless the model is an inverse model).
I'm assuming that `connect(src.input, clk.output)` yields the right answer, but as a casual reader trying to figure out what a `ContinuousClock` is, the causal direction helps understand what's going on.
> DOCS: Connect the clock in causal direction

- src/Thermal/HeatTransfer/sensors.jl
- test/Thermal/motor.jl
- test/Thermal/piston.jl
- test/Thermal/thermal.jl
https://github.com/SciML/ModelingToolkitStandardLibrary.jl/issues/384
Using RealOutputs for thermal sensors.  Note that any existing usage of temperature sensors will need to be updated (i.e. referencing of sensor output goes from T -> T.u).  Connections to sensor output are now possible.   Thermal sensors are now following the same style as those in Rotational with sensor output on connectors.  
Removing usage of OrdinaryDiffEqDefaults in tests
- [ x] Appropriate tests were added
- [x ] Any code changes were done in a way that does not break public API
- [x ] All documentation related to code changes were updated
- [ x] The new code follows the
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style …
> RealOutputs for thermal sensors

- docs/src/tutorials/input_component.md
- src/Blocks/sources.jl
- test/Blocks/sources.jl
> Interpolation with the model macro

- docs/src/connectors/connections.md
- src/Mechanical/TranslationalPosition/components.jl
- test/Mechanical/translational.jl
The initializations produced by the `TranslationalPosition` components are very overconstrained. I think that there were some initialization workarounds that were needed in the past, but on more modern MTK versions these should no longer be needed.
One  of the things that I removed is the  equations that were`flange.s` from higler level components shuch as the `Spring` and `Damper`. Is this breaking?
> Fix initialization for TranslationalPosition and add more tests

- docs/src/API/electrical.md
- docs/src/tutorials/MOSFET_calibration.md
- src/Electrical/Analog/mosfets.jl
- src/Electrical/Electrical.jl
- test/Electrical/analog.jl
> Add NMOS PMOS Transistors
